# Generated by Django 5.1.3 on 2024-12-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='objective',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prize',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=500),
        ),
    ]
